title: Haoyu Zhang's Homepage
page-top-title: Haoyu Zhang
top-section-bg-text: Operations Research Engineer
home-subtitle: Haoyu Zhang | M.S. student, Operations Research
copyright-text: '&copy; Haoyu Zhang 2026-2029. All Rights Reserved.'
