title: Haoyu Zhang's Homepage
page-top-title: Haoyu Zhang
top-section-bg-text: Operations Research
home-subtitle: Haoyu Zhang | 张皓宇
copyright-text: '&copy; Haoyu Zhang 2026-2029. All Rights Reserved.'
